### PR TITLE
move swift rule to sep. file in prom frontend

### PR DESCRIPTION
**Pull request by auhlig**
move rule avg:swift_cluster_storage_used_percent_gauge{} to separate swift.rules in prom. frontend
Looks good @majewsky?

/cc @reimannf More swift rules could go here `system/kube-monitoring/charts/prometheus-frontend/swift.rules`

### CODE REVIEW

**Comment by majewsky** [comment]
I don't think this is necessary. It's not like these are different concerns. The rules for Swift are still aggregation rules.

**Comment by auhlig** [comment]
If it stays in the collector, then the metric won't be available in the frontend. 
I could rename the file to aggregation.rules

**Comment by majewsky** [comment]
Ah, one is in the collector and the other is in the frontend.

In that case, I reject this proposal for being unecessarily obscure. :) We have already established a pattern with the `aggregated:` metrics, which are aggregated in the collector and pulled into the frontend [here](https://github.com/sapcc/helm-charts/blob/fe88b65fab3d6648f3209886e61a554598fe0ab2/system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml#L35). If we follow that pattern, there are two options:

1. add another match on `__name=~"^avg:.+"` in there
2. rename the metric to `aggregated:swift_cluster_storage_used_percent_gauge` (which is what I would prefer)

**Comment by auhlig** [comment]
Convincing. Then option 2 it will be.

**Comment by auhlig** [comment]
To avoid confusion with existing metrics, the new one is called `aggregated:swift_cluster_storage_used_percent_gauge_average`.
Good to merge @majewsky ?

**Pull request merged**
