### PR TITLE
kube-monitoring-*, kube-system-*: bump all deps to latest

### PR DESCRIPTION
**Pull request by majewsky**
So we can then pull in the API version upgrades without any overlapping changes.

### CODE REVIEW

**Comment by auhlig** [comment]
Can you sync the lock file to make the tests green?

**Comment by auhlig** [comment]
Potentially the only thing we need to keep an eye on is `kube-proxy` being bumped to `0.6.23` in virtual clusters @defo89 

- The `kube-system-abapcloud` chart is no more. Kustomize all the way.
- `vice-president` is replaced by digicert-issuer + cert-manager

**Comment by defo89** [comment]
> Potentially the only thing we need to keep an eye on is `kube-proxy` being bumped to `0.6.23` in virtual clusters @defo89

It's ok to bump `kube-proxy` to `0.6.23` in virtual.

**Review by defo89 — APPROVED** [review]
lgtm

**Pull request merged**
