### PR TITLE
prometheus frontend as deployment

### PR DESCRIPTION
**Pull request by auhlig**
As simple as this? Ok to test in staging?
Please **do not merge** yet.

### CODE REVIEW

**Comment by BugRoger** [comment]
Looks good from my side. Good catch @majewsky.

You can try in staging. If we lose that 30GB of data, it would probably be a good thing even... :D

**Comment by majewsky** [comment]
It definitely needs to be tested in staging, but Arno should coordinate at least with @reimannf while the Swift load tests are in progress.

**Comment by auhlig** [comment]
Sure. I've sent a mail.
Rolling this out to staging is scheduled for tomorrow morning

**Comment by auhlig** [comment]
works fine. also able to reuse existing pvc.

**Pull request merged**
