### PR TITLE
[vrops-exporter] new self and nsxt alert definitions

### PR DESCRIPTION
**Pull request by richardtief**

### CODE REVIEW

**Comment by christopherhans** [comment]
There are new warning alerts added. Are they replacing existing ones or are the completely new?

**Comment by richardtief** [comment]
Yes, as discussed we bring everything in on info. I create an extra pull request for raising to `warning` and `critical`.

**Comment by richardtief** [comment]
> There are new warning alerts added. Are they replacing existing ones or are the completely new?

Both, some are new some are replacing existing ones.

**Review by christopherhans — APPROVED** [review]
Thank you

**Pull request merged**
