### PR TITLE
*WIP* Enable Debezium Change-Data-Capture on Postgres and MariaDB

### PR DESCRIPTION
**Pull request by jobrs**
Postgres
* use image with required plugins
* enable logical write-ahead logging
* permit WAL consumers to connect and consume WAL segments

Open Issues
- [ ] create database user for Debezium
- [ ] make sure Kafka Connect (scale-out cluster) can connect to Postgres/MariaDB (e.g. verify pg_hba.conf settings)
- [ ] implement also for MariaDB

### CODE REVIEW

**Comment by jobrs** [comment]
in-preparation ... see https://issues.wdf.sap.corp/browse/CCM-8115

**Comment by jobrs** [comment]
updated: KafkaConnect moves into the control-plane. Namespace "eventhub"

**Comment by stefanhipfel** [comment]
Hi, do we need to upgrade to postgres v. 9.6 and use the debezium image?

**Comment by jobrs** [comment]
Hi Stefan,

the major addition they made are the two logical decoding plugins. You missed them or are they installed by other means?

If we stick with our current helm chart (derived from the "official" one as of 9.5), we should be able to use the Debezium image as a plugin replacement. Thats no longer the case with later versions of the official helm chart.

**Comment by stefanhipfel** [comment]
I removed the changes in the values file, since this is the default for all our services. If they are not overwritten in the services charts, they will fall back to default. 
That is why we cannot set anything debezium specific in the defaults

**Comment by jobrs** [comment]
that's fine, meanwhile only decoderbufs is needed

https://github.wdf.sap.corp/cc/realtime-inventory/commit/5eaee7b546921503008cfb03d91582ec9d007ec9

**Pull request merged**
