### PR TITLE
[rabbitmq] fix permissions if persistence is enabled

### PR DESCRIPTION
**Pull request by Carthaca**
`fsGroupChangePolicy: "OnRootMismatch"`does not work for NFS mounts
(also see kubernetes/examples/issues/260)

### CODE REVIEW

**Comment by fwiesel** [comment]
That can get very expensive... we need to do something like `OnRootMismatch` in the script.
Untested, but maybe like this:
```yaml
command:
- /bin/sh"
- -c
- |
- [ $(stat -c %u /var/lib/rabbitmq) == 999 ] || chown -R 999:999 /var/lib/rabbitmq
```

**Comment by Carthaca** [comment]
> That can get very expensive... we need to do something like `OnRootMismatch` in the script. Untested, but maybe like this:
> 
> ```yaml
> command:
> - /bin/sh
> - -c
> - |
> - [ $(stat -c %u /var/lib/rabbitmq) -eq 999 ] || chown -R 999:999 /var/lib/rabbitmq
> ```

Good idea, I added this and tested in qa. Thanks!

**Review by fwiesel — APPROVED** [review]

**Review by bashar-alkhateeb — CHANGES_REQUESTED** [review]
please add a change description to the CHANGELOG.md

**Comment by Carthaca** [comment]
> please add a change description to the CHANGELOG.md

done

**Review by bashar-alkhateeb — APPROVED** [review]

**Pull request merged**
