### PR TITLE
[maia][storage] add netapp_snapmirror.*:maia metrics

### PR DESCRIPTION
**Pull request by chuan137**
the more general expression includes metrics 'netapp_snapmirror.*:maia' into federation

### CODE REVIEW

**Review by richardtief — APPROVED** [review]
Thanks.

**Review by viennaa — CHANGES_REQUESTED** [review]
please bump patch version of the chart

**Comment by viennaa** [comment]
Can you specify in the commit message, which metrics you are actually adding with this commit? Ran this in qa and there are only 6 more hits with this adjusted query.

**Comment by chuan137** [comment]
> Can you specify in the commit message, which metrics you are actually adding with this commit? Ran this in qa and there are only 6 more hits with this adjusted query.

the new metrics are `netapp_snapmirror_*`, do you see them in qa?

**Review by viennaa — APPROVED** [review]
Thanks, good to go!

**Review by notque — APPROVED** [review]
LGTM

**Pull request merged**
