### PR TITLE
[nova] Switch to Chart v2 format

### PR DESCRIPTION
**Pull request by fwiesel**

### CODE REVIEW

**Comment by joker-at-work** [comment]
Care to rebase this? Sorry for not looking into it earlier :/

**Comment by fwiesel** [comment]
Now based on the latest commit

**Review by joker-at-work — COMMENTED** [review]
It looks like it's missing the removal of `requirements.yaml` now.

**Comment by fwiesel** [comment]
True, now I removed it.

**Review by joker-at-work — APPROVED** [review]

**Pull request merged**
