### PR TITLE
Add CRC error alert definition

### PR DESCRIPTION
**Pull request by mithunmgore**
Added info alert for CRC errors.

Signed-off-by: Mithun Gore <mithungore@gmail.com>

### CODE REVIEW

**Review by christopherhans — CHANGES_REQUESTED** [review]
The alert is missing tier & service. This is important for the alert routing. Please add
```
tier: vmware
service: compute
```
i.e.: https://github.com/sapcc/helm-charts/blob/master/prometheus-exporters/vrops-exporter/alerts/virtualmachine.alerts#L13-L14

**Review by christopherhans — APPROVED** [review]
@viennaa pls merge

**Comment by viennaa** [comment]
Shouldn't there be a `for` condition in there too?

**Comment by christopherhans** [comment]
As the CRC alerting conditions are not 100% sure, we agreed with Martin&Biswajit to create the definition as in this PR. The Ops colleagues will actively monitor the alert in the info channel and decide if further adjustments are needed.

**Comment by viennaa** [comment]
Alright, your call.

**Pull request merged**
