### PR TITLE
[rabbitmq] Move setup script to secret

### PR DESCRIPTION
**Pull request by fwiesel**
The script contains credentials, and is therefore a secret.

### CODE REVIEW

**Comment by fwiesel** [comment]
I haven't really tested it.

**Comment by bashar-alkhateeb** [comment]
> I haven't really tested it.

I will take care of testing it, and will let you know

**Comment by dusandordevicsap** [comment]
I tested this and it fails. It seems that helm renders chart OK, but it fails on K8S side with following errors:

```
W0115 14:44:13.090284   35127 warnings.go:70] unknown field "spec.template.spec.volumes[1].secret.name"
Error: INSTALLATION FAILED: 2 errors occurred:
	* Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 0
	* Deployment.apps "oslo-simulator-quorum-rabbitmq" is invalid: [spec.template.spec.volumes[1].secret.secretName: Required value, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "container-init"]

```

**Comment by fwiesel** [comment]
Stupid me... I'll fix it.

**Comment by dusandordevicsap** [comment]
This fixed Secret... error, but other one is still there:

```
helm.go:84: [debug] 1 error occurred:
	* Deployment.apps "oslo-simulator-quorum-rabbitmq" is invalid: [spec.template.spec.volumes[1].secret.secretName: Required value, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "container-init"]

```

**Comment by dusandordevicsap** [comment]
Yes, solved. I managed to install it using Oslo-simulator and everything looks operational

**Pull request merged**
