### PR TITLE
[nova] adds dbUser to globals. Fixes pgmetrics auth error!

### PR DESCRIPTION
**Pull request by stefanhipfel**
…efault dbuser

### CODE REVIEW

**Comment by stefanhipfel** [comment]
the dbuser is not setup in globals, therefor pgmetrics will use the default user (postgres):
https://github.com/sapcc/helm-charts/blob/master/common/pgmetrics/templates/deployment.yaml#L41

We also have pgmetrics  deployment in the postgresql charts. I think we should remove it!

**Comment by notandy** [comment]
Hi,

I would also like to see the metrics using the .Values.db_user, or even better using the local postgres domainsocket as Postgres user without authentification, this would provide metrics even if pgbouncer are unable to connect (e.g. due to pool exhaustion).

**Comment by fwiesel** [comment]
We moved away from a local socket, as that requires the container to be in the same pod, and that would mean restarting the pod on a metric change.

Using a domain-scheduling would require some tricks with scheduling hostpaths, or localstorage.

**Comment by notandy** [comment]
ah ok, make sense (when does kubernetes support restart of single containers!?!).
can we use the postgres user for metrics?

**Comment by fwiesel** [comment]
Now that I think about it, we could co-locate the containers, but we would need a shared pid-space.
Then we could add another side-car container, which would trigger a restart of the metric container (e.g. kill the corresponding process), if the metric config changes.

Alternatively, we could patch the exporter to monitor the file for changes, which would eliminate the need for external changes.

**Comment by stefanhipfel** [comment]
This was meant as a quick fix. Merge it if you want it, as I am away on a short trip.

**Pull request merged**
