### PR TITLE
[ironic] Remove superflous coordination section

### PR DESCRIPTION
**Pull request by fwiesel**
Instead of using the memcached driver, we can use
the PVC which should be more robust with respect
to restarts of the nodes

### CODE REVIEW

**Comment by fwiesel** [comment]
Only draft, as the proper work only makes sense after merging all the other PRs

**Comment by fwiesel** [comment]
Depends on #3851

**Review by stefanhipfel — APPROVED** [review]
hm just wondering why the inspector needs locking and not the conductors

**Comment by fwiesel** [comment]
I just blindly replaced the configuration... but good point. I almost suspect it is a superfluous configuration.

**Comment by fwiesel** [comment]
It is... maybe it was used once, but now it does locking via the database and uses a hashring for coordination.

**Pull request merged**
