### PR TITLE
[mariadb] initdb secret is required during install

### PR DESCRIPTION
**Pull request by Carthaca**

### CODE REVIEW

**Review by fwiesel — APPROVED** [review]

**Comment by galkindmitrii** [comment]
I think you might need to decrease the `"helm.sh/hook-weight"` for it to work correctly.

**Review by galkindmitrii — APPROVED** [review]

**Comment by businessbean** [comment]
Hi Maurice, let me think about it...

**Review by bashar-alkhateeb — APPROVED** [review]
Looks good !

**Review by businessbean — APPROVED** [review]
lgtm

**Pull request merged**
