### PR TITLE
[manila][mariadb][rabbitmq][utils] Bump up mariadb,rabbitmq, utils for Manila

### PR DESCRIPTION
**Pull request by dusandordevicsap**
Bump up subcharts :
-- rabbitmq to version 0.6.10 (rabbitmq version 3.13.0)
-- mariadb to version 0.9.2
-- utils to version 0.15.0
Switch to set the new mariadb values initdb_secret instead of initdb_configmaps
Replace proxysql config map with proxysql secret
Activate detailed metrics

### CODE REVIEW

**Comment by Carthaca** [comment]
Is `proxysql-secret.yaml` (the replacement for `proxysql-configmap.yaml`) missing?

**Comment by galkindmitrii** [comment]
Also MariaDB still has gaps, this PR has to be merged first: https://github.com/sapcc/helm-charts/pull/6286

**Comment by galkindmitrii** [comment]
This needs another bump of all deps (mariadb/rabbitmq/utils)

**Comment by Carthaca** [comment]
done: bumped again (mariadb still on 9.x, I want to test the passwordless root user change separately)
and added the proxysql secret

**Comment by dusandordevicsap** [comment]
Shall I merge all of this then ?

**Comment by Carthaca** [comment]
> Shall I merge all of this then ?

We need approval first, @galkindmitrii / @chuan137 can you give this, please? (I disqualified by committing myself)

**Review by galkindmitrii — APPROVED** [review]

**Comment by Carthaca** [comment]
yeah - on purpose

> I want to test the passwordless root user change separately

**Comment by Carthaca** [comment]
ah.. the 0.10 feature is opt-in I just noticed - I can do the additional bump than safely

**Pull request merged**
