### PR TITLE
[alertmanager] add OSD pagerduty keys

### PR DESCRIPTION
**Pull request by geisslet**
add one service desk pagerduty service on request for monitor of monitors - check with MR was done

pls-check/merge kube-secret on values before

### CODE REVIEW

**Comment by auhlig** [comment]
Tests are failing with this config. Can you check?
https://ci.eu-de-2.cloud.sap/builds/563562#L5f50798c:63

**Comment by geisslet** [comment]
thanks for check
on the issue: yeah, because there is a kube/secret isn't merge yet (keys missing) - there is also a request

**Comment by geisslet** [comment]
oh sorry .. you did! .. will check!

**Comment by geisslet** [comment]
@auhlig could you pls re-review and do the rollout / tell me that I shall? //thanksInAdvance

**Review by auhlig — APPROVED** [review]

**Comment by auhlig** [comment]
LGTM. Will be deployed today

**Pull request merged**
