### PR TITLE
Updated snmp generator and metrics for F5

### PR DESCRIPTION
**Pull request by m-kratochvil**
This update covers memory monitoring

### CODE REVIEW

**Comment by m-kratochvil** [comment]
@thgrs

**Comment by Kuckkuck** [comment]
If the generator is doing the config, than it doesn't make sense to update the generated config in the helm charts. Just chance the f5-generator.yaml and run the pipeline to generate a new config for f5.

**Comment by m-kratochvil** [comment]
I fixed the metrics file, now it holds only the OIDs as it's supposed to.
@Kuckkuck @thgrs

**Comment by m-kratochvil** [comment]
@thgrs

**Pull request merged**
