### PR TITLE
[nova] update dependency on rabbitmq to version 0.5.2

### PR DESCRIPTION
**Pull request by bashar-alkhateeb**
adding vendor's feature enhancements and bug fixes: rabbitmq-3.11.15-management
[ChangeLog](https://www.rabbitmq.com/changelog.html)

### CODE REVIEW

**Comment by fwiesel** [comment]
See: https://github.com/sapcc/helm-charts/pull/5185#issuecomment-1635437392

**Review by fwiesel — COMMENTED** [review]
Fine by me. What's your take @grandchild ?

**Comment by grandchild** [comment]
Still confused.

The defaults from the rabbitmq chart are:

https://github.com/sapcc/helm-charts/blob/master/common/rabbitmq/values.yaml#L71-L74

```yaml
metrics:
  enabled: &metrics true
  sidecar:
    enabled: *metrics
```

and in the nova chart we have:

https://github.com/sapcc/helm-charts/blob/11aaecdef5cf68dc14be22742711d3ed3c0aaa8b/openstack/nova/values.yaml#L802-L811

```yaml
rabbitmq:
  [...]
  metrics:
    password: null
```

which sounds to me like we will have the explicit sidecar and not the plugin.

but in the meeting i understood we don't want the sidecar anymore? or do we, @fwiesel?

**Comment by fwiesel** [comment]
No, since the metrics come from rabbitmq plugin, the sidecar is just dead weight.

**Comment by bashar-alkhateeb** [comment]
first you need to merge this PR :)
https://github.com/sapcc/helm-charts/pull/4620/files

**Comment by bashar-alkhateeb** [comment]
we didnt change the default config of rabbitMQ chart to be sure that all services moved ''in a planned way'' to the new config and after then we will change the default config

**Comment by grandchild** [comment]
so we should merge #4620, then roll out nova, and then merge this, right?

**Comment by grandchild** [comment]
or can we do it in one deployment?

**Comment by bashar-alkhateeb** [comment]
yes you can

**Review by grandchild — APPROVED** [review]

**Comment by grandchild** [comment]
oops

**Pull request merged**
