### PR TITLE
[vrops] split critical alerts to different managed service related vo…

### PR DESCRIPTION
**Pull request by geisslet**

### CODE REVIEW

**Review by viennaa — APPROVED** [review]
Approved, it is going to be routed to different channels.

**Comment by viennaa** [comment]
@christopherhans please merge and deploy beginning of next week.

**Comment by christopherhans** [comment]
@viennaa I don't have write access.

**Comment by geisslet** [comment]
@killermoehre fyi

**Comment by christopherhans** [comment]
Change rolled out globally.

**Pull request merged**
