### PR TITLE
[mariadb-galera] Helm chart and Dockerfile for MariaDB Galera and supporting tools added

### PR DESCRIPTION
**Pull request by businessbean**
- [MariaDB](https://mariadb.com/kb/en/documentation/) extended with the [Galera library](https://mariadb.com/kb/en/what-is-mariadb-galera-cluster/) to provide a synchronous database cluster running in Kubernetes
- automated initial bootstrap and full restarts
- startup, liveness and readiness checks to let Kubernetes automate the lifecycle of the pods and services
- prestop scripts to ensure clean pod restarts
- block and file storage support for the persistent volumes
- dedicated volumes for MariaDB transaction logs
- database configuration without pod restarts
- support for running as (Openstack) chart dependency
- optional Prometheus metrics provided by [mysqld_exporter](https://github.com/prometheus/mysqld_exporter) as sidecar
- [ProxySQL](https://www.proxysql.com/) option to enable traffic routing and to hide MariaDB pod restarts
- [HAproxy](http://www.haproxy.org/) option to provide faster loadbalancing without traffic routing in progress
- automated encrypted backups using [Kopia](https://kopia.io/) supporting NFS and S3/Swift backends
- semi automated (point in time) recoveries using Helm chart options
- [sysbench](https://github.com/akopytov/sysbench) integration for performance and availability tests
- documentation generated with [helm-docs](https://github.com/norwoodj/helm-docs)
- workflow diagrams based on [Mermaid](http://mermaid.js.org/)
- automated integration tests available in Concourse
- automated Docker image builds available in Concourse

### CODE REVIEW

**Review by bashar-alkhateeb — COMMENTED** [review]
would you kindly rebase first to solve the conflicts ?
i would prefer having less commits in the PR just to review the commit messages as well, which can document this feature in more details ? that instead squashing while merging in the WebUI, what do you think?

**Comment by businessbean** [comment]
> would you kindly rebase first to solve the conflicts ? i would prefer having less commits in the PR just to review the commit messages as well, which can document this feature in more details ? that instead squashing while merging in the WebUI, what do you think?

Hi Bashar, there are no conflicts.
image

I have a summary in the PR message to avoid that you have to read all the commit messages. `squash and merge` will create one commit that will be merged into master.
image

**Comment by businessbean** [comment]
@bashar-alkhateeb the `rebase and merge` option reports conflicts. The local interactive rebasing also shows conflicts for multiple commits. I think we should chose the `squash and merge` option to merge one commit into master and to avoid fixing all the merge conflicts in outdated commits.

**Comment by businessbean** [comment]
Superseded by https://github.com/sapcc/helm-charts/pull/6519

**Pull request closed without merging**
