### PR TITLE
[vrops-exporter] Extract tag from summary|tagJson

### PR DESCRIPTION
**Pull request by max-len**
This was tested for one existent tag with the label_replace function and therefore needs further testing as relabel config, with multiple tags of different categories etc.
It might be possible to generalize it even more to create new labels for all objects in the tag json, although it could be difficult for multiple tags of the same category.

### CODE REVIEW

**Review by kevin-fischer — APPROVED** [review]
+1

**Review by richardtief — COMMENTED** [review]
Looks good. But I'm not sure if you want to leave out the original label then.

https://github.com/sapcc/helm-charts/blob/3ac69c601b7b476eb852ebd47517ab638df794a3/system/vmware-monitoring/templates/vrops-exporter-deployment.yaml#L124-L125

**Comment by richardtief** [comment]
@max-len this pr is still open.

**Review by richardtief — APPROVED** [review]
Thanks, all good

**Pull request merged**
