### PR TITLE
[manila] fix share from snapshot config option

### PR DESCRIPTION
**Pull request by Carthaca**
see https://github.com/sapcc/manila/blob/3aff6a6621bf265780db5ef3370741d1aac915e4/manila/share/driver.py#L47

### CODE REVIEW

**Review by kpawar-sap — APPROVED** [review]

**Review by chuan137 — COMMENTED** [review]
thx and nice pick. Just remind me pls, what is the reason for the if-branch for value 100?

**Comment by Carthaca** [comment]
> seems that we have used the fallback value of the `reserved_share_percentage`. we are going to set different values for this option now?

yes, that has always been the intention to have a lower reserve for shares from snapshot - we don't allow shares from snapshots to be scheduled somewhere else, so we allow those, even when we don't want regular new shares any more

**Comment by Carthaca** [comment]
> thx and nice pick. Just remind me pls, what is the reason for the if-branch for value 100?

see 9c6dfb878c8a4fb79e0fa8838b9b831d941c6b15

we are not using this anymore, the reason this was needed was because of the `min` function, which would have discarded the `100`

**Review by chuan137 — APPROVED** [review]
lgtm

**Pull request merged**
