### PR TITLE
[Cinder] Remove master_password, related to https://github.com/sapcc/…

### PR DESCRIPTION
**Pull request by rajivmucheli**
…helm-charts/issues/2293

### CODE REVIEW

**Comment by rajivmucheli** [comment]
Hi @hemna,

Please validate this PR, its related to https://github.com/sapcc/helm-charts/issues/2293.

Regards,
Rajiv

**Comment by hemna** [comment]
I'm not sure how to test this without merging it

**Comment by joker-at-work** [comment]
> I'm not sure how to test this without merging it

Copy the changes to your local helm-charts. Run `helm-template-app` and verify the generated charts look ok. Change your local secrets by removing the `cinder_service_password` from $region/values/globals.yaml for the region you're testing in. Re-run `helm-template-app` and verify that chart generation fails.

Make sure that in every region the values/globals.yaml contains a `cinder_service_password`. If one doesn't you need to add it before rolling this commit to the region.

**Comment by hemna** [comment]
ok I tested this as described by johannes and it worked.  lgtm

**Comment by rajivmucheli** [comment]
I guess we missed removing `identity.password_for_user` at https://github.com/sapcc/helm-charts/blob/master/openstack/cinder/templates/etc/_cinder.conf.tpl#L65, do i need to raise another PR ?

**Pull request merged**
