### PR TITLE
[neutron] use neutron service-account for accessing nova and designate

### PR DESCRIPTION
**Pull request by notandy**
This changes neutron.conf to use it's own neutron service account for accessing foreign services instead of foreign ones. This makes requester easier identifiable and removes external dependency global service passwords.

Please ensure, that the neutron service user has all needed roles to access the respective service.

### CODE REVIEW

**Review by joker-official — CHANGES_REQUESTED** [review]
I think `neutron` needs to become `cloud_dns_admin` for this to work.

**Comment by joker-official** [comment]
Also, I would really prefer if the PR description would also be in the commit message. It's easier to find that way in a couple of years.

**Comment by joker-at-work** [comment]
`neutron` is still missing the appropriate rights to access designate as admin, afaics.

**Comment by notandy** [comment]
I added the missing role for neutron: https://github.com/sapcc/helm-charts/commit/4f1bd6bc9f2323afc955096d78e92962cad9d58e

going to merge this commit

**Comment by galkindmitrii** [comment]
Thanks Andy!

**Pull request merged**
