### PR TITLE
remove reference to deprecated tier: moni(tor)

### PR DESCRIPTION
**Pull request by artherd42**
tier: moni(tor) is depreacted, prep retirement of #alert-moni-* channels

### CODE REVIEW

**Review by richardtief — APPROVED** [review]
Thanks for removing this finally. Added some more findings to clean up the repository.

**Review by viennaa — CHANGES_REQUESTED** [review]
Thanks for bringing this up. We need to bump the affected charts additionally to the changes itself.

**Comment by richardtief** [comment]
Sounds reasonable. Will take care.

**Review by viennaa — APPROVED** [review]
Thanks, good to go!

**Comment by artherd42** [comment]
@geisslet Are you okay with removing from pager2slack?

**Comment by richardtief** [comment]
@artherd42 This is still open.

**Review by geisslet — APPROVED** [review]

**Pull request merged**
