### PR TITLE
[common/mariadb] Use backup-user with connection limit

### PR DESCRIPTION
**Pull request by fwiesel**
Instead of using the root-user, use a dedicated user with
its own connection limit in order to isolate the
backup process from the main application

### CODE REVIEW

**Review by viktor-kovacs — APPROVED** [review]
Hi, It look fine to me

**Review by IvoGoman — APPROVED** [review]
Looks good to me.
Once this is rolled out to the services I will use this user as well for the replication to metis.

**Comment by fwiesel** [comment]
I would like to create a separate user for metis. Users do not cost anything compared to the effort/risk when one application misbehaves. Do all services need a metis user?

**Comment by fwiesel** [comment]
Either way, let's move forward with this solution, and then we can improve on that.

**Comment by IvoGoman** [comment]
> I would like to create a separate user for metis. Users do not cost anything compared to the effort/risk when one application misbehaves. Do all services need a metis user?

Currently the replication is enabled for nova, neutron, glance, ironic, designate, keystone and soon also for nova-api.

**Pull request merged**
