### PR TITLE
[cinder] Integrate locking via pvc

### PR DESCRIPTION
**Pull request by fwiesel**
Instead of using the memcached driver, we can use
the PVC which should be more robust with respect
to restarts of the nodes

### CODE REVIEW

**Comment by fwiesel** [comment]
Requires #3851 to be merged in order to update the chart dependencies, otherwise good to go

**Comment by fwiesel** [comment]
Depends on #3851

**Comment by hemna** [comment]
Can you explain this a bit more?   I'm not sure I understand the change away from memcached to a file ?

**Comment by fwiesel** [comment]
I've now added an explanation to #3851, as the PRs for the other services may raise the same question.

**Comment by fwiesel** [comment]
By default, this change should only differ in the proxysql version (if that is enabled, as in qa). Otherwise, the diff should be empty.
It will allow us to enable taking locks on a share instead in memcached, so a restart of memached would not result in locks getting lost.

**Comment by fwiesel** [comment]
Merged via 3c9dc7d89557eb0bc829fa040ecbf47105e794e0

**Pull request closed without merging**
