### PR TITLE
alertmanager: add #cc-os-repo, remove #cc-os-cfm

### PR DESCRIPTION
**Pull request by majewsky**

### CODE REVIEW

**Review by bassel-z — CHANGES_REQUESTED** [review]
LGTM. However, please just pump the version of ALM chart with this change

**Comment by majewsky** [comment]
By ALM chart, I'm guessing you mean `global/prometheus-alertmanager-operated`? If so, then done.

**Review by bassel-z — APPROVED** [review]
LGTM

**Comment by bassel-z** [comment]
> By ALM chart, I'm guessing you mean `global/prometheus-alertmanager-operated`? If so, then: Done.

yes

**Pull request merged**
