### PR TITLE
Disentangle kubemon maia

### PR DESCRIPTION
**Pull request by jobrs**
* stop scraping Maia exporters from kube-monitoring prometheus-collector. No Maia metrics will be stored in kube-monitoring. Instead Grafana can collect data from both kube-monitoring and maia-prometheus if needed. New datasource has been added to Grafana content as well.
* minimize cross-federation from kube-monitoring prom-coll to maia in favor of parallel scraping of exporters
* facilitate the above by using discovery instead of static_configs
   - maia.io/scrape marks services to be scraped by Maia's Prometheus
   - maia.io/scrape_param_<xyz> marks service which need URL-parameter <xyz>

@BugRoger: Before you merge, maia needs to get access to the Kubernetes API like you did today for staging.

### CODE REVIEW

**Comment by BugRoger** [comment]
lgtm

**Comment by thgrs** [comment]
sounds like a good idea - fine with me

**Comment by thgrs** [comment]
i would be interested to know how this is done: "Before you merge, maia needs to get access to the Kubernetes API like you did today for staging." - i looked into this with @auhlig a while ago, but it looked quite complicated with the current kubernetes version we are using.

**Comment by auhlig** [comment]
I think @BugRoger gave the service-account in the maia ns sufficient permissions, right?

**Comment by BugRoger** [comment]
I renamed the authorizations for `monasca` to `maia` in staging. The same needs to be done in regions who had Monasca deployed before. In new regions we need to add this line. https://github.wdf.sap.corp/monsoon/monsoon3/commit/36d39439bea37906ea398f94f15cc4a92becc6b1

**Pull request merged**
