### PR TITLE
separate manila-nanny to own chart

### PR DESCRIPTION
**Pull request by chuan137**

### CODE REVIEW

**Comment by Carthaca** [comment]
The prometheus-aggregations + recording rules and the manila-service should be moved, too

**Comment by chuan137** [comment]
> The prometheus-aggregations + recording rules and the manila-service should be moved, too

I am wonering what the purpose of the aggregations rule is for. The dashboard https://grafana.qa-de-1.cloud.sap/d/manila-nanny-summary/manila-nanny-summary?orgId=1 provides a pretty good overview of the potential issues.

The manila-service is left out on purpose, because I added the prometheus scrape annotations and metrics ports into the pod.

**Comment by Carthaca** [comment]
> I am wonering what the purpose of the aggregations rule is for. The dashboard https://grafana.qa-de-1.cloud.sap/d/manila-nanny-summary/manila-nanny-summary?orgId=1 provides a pretty good overview of the potential issues.

e.g. https://grafana.qa-de-1.cloud.sap/d/manila-nanny-summary/manila-nanny-summary?viewPanel=5&orgId=1 uses the metric `openstack_manila_nanny_missing_volume_count` from prometheus-global, wouldn't that stop working without that rule?

**Comment by Carthaca** [comment]
Ah just saw the last commit, but it also needs the related template https://github.com/sapcc/helm-charts/blob/master/openstack/nannies/templates/prometheus-aggregations.yaml

**Review by Carthaca — APPROVED** [review]
👍

**Pull request merged**
