### PR TITLE
Change openstack-service-critical to critical-infrastructure PriorityClass

### PR DESCRIPTION
**Pull request by Nuckal777**
Migrate old PriorityClass to the equivalent one in the new scheme. openstack-service-critical will stay in the metal cluster for now.

### CODE REVIEW

**Review by joker-at-work — APPROVED** [review]

**Review by galkindmitrii — COMMENTED** [review]
Don't we need to bump chart versions respectively?

**Comment by businessbean** [comment]
Let me bump the chart versions...

**Review by businessbean — APPROVED** [review]
Thanks for the PR. lgtm

**Comment by s10** [comment]
@auhlig @defo89 , please take a look at this PR.

**Pull request merged**
