### PR TITLE
[mariadb] add alert on pod not being ready for 5 minutes.

### PR DESCRIPTION
**Pull request by galkindmitrii**
For now as a warning, will be promoted to critical after testing.

### CODE REVIEW

**Comment by galkindmitrii** [comment]
ping, anyone?

**Review by joker-at-work — COMMENTED** [review]
I don't see anything wrong with this, but I think Warning alerts should be approved by someone from team supervision.

**Comment by galkindmitrii** [comment]
tagging @artherd42

**Review by artherd42 — APPROVED** [review]
Please do a handover to B1 before this alert is set critical.

**Pull request merged**
