### PR TITLE
Pyroscope: Request linkerd

### PR DESCRIPTION
**Pull request by fwiesel**

### CODE REVIEW

**Review by joker-at-work — COMMENTED** [review]
This doesn't seem to add any linkerd annotations I could see. Does it work like that? I thought we'd have to edit the `Deployment` and `Service` definitions to add the annotations.

**Comment by fwiesel** [comment]
Sorry, I thought there was more magic happening. Now, I've set the values,  and checked it in a diff.

**Review by joker-at-work — APPROVED** [review]
The global option `linkerd_requested` has basically no functionality - shall we keep it as a hint that we have linkerd?

**Comment by fwiesel** [comment]
I'd say yes. Mostly  so we can grep it.

**Pull request merged**
