### PR TITLE
[neutron] openvswitch mtu fix, neutron-openvswitch-agent-start is the only file that needs changing.

### PR DESCRIPTION
**Pull request by sapliedtke**
I think this is only one half of the solution, Ignition needs to make sure the network nodes have the correct MTU sizes as well

### CODE REVIEW

**Comment by notandy** [comment]
looks okay, even though the same interface is configured by two startup scripts.

**Comment by sapliedtke** [comment]
different pods/container, we might even have to add more.

**Comment by notandy** [comment]
yeah different pods, but same interface. The pods are using the host network namespace, so it's the same device

**Comment by sapliedtke** [comment]
youre correct and it seems ovs-tools are working differently then i anticipated, back to the drawing board, we need to iterate through quite a few interfaces.

**Comment by abattye** [comment]
I'm not sure this will work the script is working on value "cp_network_interface" as $interface. This is usually bond1. So  https://github.com/sapcc/helm-charts/pull/574/files#diff-74a8f112c7e5ce81dc59c3ce9d57c6e1R55 should I think read `ovs-vsctl set int br-${interface} mtu_request=9000`

**Comment by sapliedtke** [comment]
yeah that PR was from when i didnt know yet how the setup works. Marian and Sebastian had a call with me on Friday where they told me what they know and we together figured out the right solution.
Expect a working PR by Monday Morning.

**Comment by abattye** [comment]
Please don't hardcode bond1 - its configurable and can be accessed in the form br-${interface} - so the helm variable ${interface} should be used

**Comment by sapliedtke** [comment]
ah ok, i wasnt sure about the variables, will update during my next shift, else its ok?

**Comment by sapliedtke** [comment]
can someone point me to where those variables are defined? maybe another repo? im still learning these charts.

**Pull request closed without merging**
