### PR TITLE
[MariaDB] Uses dockerHubMirror for MariaDB image

### PR DESCRIPTION
**Pull request by IvoGoman**

### CODE REVIEW

**Comment by galkindmitrii** [comment]
Keppel itself depends on Keystone and this adds "chicken-egg" problems.
Because all Openstack services including Keystone use this DB chart.
Unless there is an automatic failover to another region and a fire-drill completed, I'd rather not have this merged.

**Comment by IvoGoman** [comment]
Was not aware of this issue. Closing the PR for now

**Comment by joker-at-work** [comment]
Don't we have `dockerHubMirrorAlternateRegion` for exactly those chicken-egg problems?

**Comment by galkindmitrii** [comment]
> Don't we have `dockerHubMirrorAlternateRegion` for exactly those chicken-egg problems?

We do, but that is still a hardcoded region with no automatic failover. There is currently a discussion to move those to ECR.

**Pull request closed without merging**
