### PR TITLE
WIP: Hermes barbican enablement

### PR DESCRIPTION
**Pull request by notque**
Work in Progress Barbican Enablement - I still need to go over and check for any issues.

### CODE REVIEW

**Comment by rajivmucheli** [comment]
Maybe the below is required :

1. rabbitmq_notifications in requirements
2. barbican_audit_map.yaml
3. values.yaml 
audit:
  enabled: true

**Comment by notque** [comment]
Here is the barbican mapping if you want to take a glance over it. https://github.com/sapcc/openstack-audit-middleware/blob/barbican_mapping/etc/barbican_audit_map.yaml

**Comment by notque** [comment]
Attempted to fix the linting issue, didn't sort it out. Will try to read more in depth on the linting and see if I can get the actual error.

**Comment by rajivmucheli** [comment]
volume mount paths have to be added to api-deployment.yaml, right ?

**Comment by notque** [comment]
due to some merge issues with git, i need to make a new branch and set these changes to it. Then delete this one, and use the new branch for ease of testing.

**Comment by notque** [comment]
Closing this PR for new branch with updated files for testing.

**Pull request closed without merging**
