### PR TITLE
allow prometheus.yaml to be extended by the regional values.yaml

### PR DESCRIPTION
**Pull request by majewsky**
I need this to make Prometheus scrape our legacy Swift nodes.

### CODE REVIEW

**Comment by majewsky** [comment]
@reimannf FYI

**Comment by BugRoger** [comment]
Hm. I'd prefer if we could use the service discovery to define the scrape targets. I suppose we are not talking about Kubernetes Nodes. This are just external additional static IPs that need to be scraped?

How about a headless service without selector? This won't be assigned a clusterIP and is just a configuration placeholder. Since there is no selector, the endpoints can be configured manually too.

```
apiVersion: v1
kind: Service
metadata:
  name: swift-legacy-nodes
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  clusterIP: none
```

Endpoints:
```
apiVersion: v1
kind: Endpoints
metadata:
  name: swift-legacy-nodes
subsets:
  - addresses:
    - ip: 1.2.3.4
    - ip: 1.2.3.5
    - ip: 1.2.3.6
    ports:
      - name: metrics
        port: 8080
        protocol: TCP
```

As a bonus you will end up with DNS resolution for this service.

**Comment by majewsky** [comment]
#TheMoreYouKnow. I didn't know that was even possible. Will try this tomorrow in staging and get back to you about this.

**Comment by majewsky** [comment]
@BugRoger's proposal works fine, so I'll close this.

**Pull request closed without merging**
