### PR TITLE
nova/flavors: Re-enable CPU reservation for hana-exclusive

### PR DESCRIPTION
**Pull request by grandchild**

### CODE REVIEW

**Comment by grandchild** [comment]
Testing is still underways, please review the contents of the config anyway: I will only merge when both review approvals _and_ testing is positive.

**Review by joker-at-work — APPROVED** [review]
Why are we only doing this for hanas on hana-exclusive hosts?

**Comment by grandchild** [comment]
> Why are we only doing this for hanas on hana-exclusive hosts?

Because CPU-reservation on mixed-workload clusters is still an open issue because of CPU overcommit. We haven't implemented a solution to "take away" the additional `reserved_cores * (overcommit - 1)` from the capacity.

**Comment by grandchild** [comment]
Testing completed successfully: Created a 48-vcpu VM & the reserved MHz in VMware * the MHz-per-vCPU value for the host == 45vCPUs, i.e. the 95%-reservation value set for the flavor.

**Pull request merged**
