### PR TITLE
prometheus-openstack: kube-state-metrics removed

### PR DESCRIPTION
**Pull request by richardtief**
With Thanos, it is no longer necessary to have `kube-state metrics` available in multiple Prometheus. Kubernetes Prometheus keeps these metrics available so that they only need to be maintained in one place. Dependent OpenStack services have been adjusted accordingly so that no absent metric alerts are generated.

@vienna for prometheus-openstack
@notque and @Kuckkuck for hermes
@majewsky for limes
@galkindmitrii for designate

### CODE REVIEW

**Review by viennaa — COMMENTED** [review]
Thanks for reducing the (now) unnecessary kube-state-metrics load here.

Please have a look at hermes linting.

**Review by viennaa — APPROVED** [review]
Thanks!

**Comment by majewsky** [comment]
Since these multi-service PRs tend to get stuck in approval limbo for longer than anyone would want, I've split the changes for Limes into a separate commit: 503352ea45306f9359b227f3720eec2f34e36575 - They can be removed from this PR.

**Review by notque — APPROVED** [review]
LGTM

**Review by galkindmitrii — APPROVED** [review]

**Comment by richardtief** [comment]
neutron: https://github.com/sapcc/helm-charts/pull/5427

**Pull request merged**
